spring:
  application:
    name: customer

integration:
  viacep:
    base-url: https://viacep.com.br/ws

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: false
  default-produces-media-type: application/json
