server:
  port: 8085

spring:
  application:
    name: order

  datasource:
    url: jdbc:h2:mem:order_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    addresses: ${RABBITMQ_URL:amqp://guest:guest@localhost:5672}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2.0
          max-retries: 5

api:
  customer:
    url: ${CUSTOMER_SERVICE_URL:http://localhost:8082}
  inventory:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8083}
  security:
    internal:
      secret: ${INTERNAL_API_SECRET:senha-secreta-microsservicos-1234}

